# Generated by Django 6.0 on 2026-01-12 18:18

import video_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=500)),
                ('thumbnail_url', models.CharField(blank=True)),
                ('thumbnail_file', models.FileField(upload_to=video_app.models.video_thumbnail_root)),
                ('category', models.CharField(choices=[('drama', 'Drama'), ('crime', 'Crime'), ('thriller', 'Thriller'), ('action', 'Action'), ('comedy', 'Comedy'), ('romance', 'Romance'), ('horror', 'Horror'), ('sci_fi', 'Science Fiction (Sci-Fi)'), ('fantasy', 'Fantasy'), ('mystery', 'Mystery'), ('adventure', 'Adventure'), ('animation', 'Animation'), ('documentary', 'Documentary'), ('family', 'Family'), ('war', 'War'), ('western', 'Western'), ('musical', 'Musical')])),
                ('video_file', models.FileField(upload_to=video_app.models.video_upload_root)),
            ],
        ),
    ]
