# Generated by Django 6.0 on 2026-01-19 05:37

import video_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=500)),
                ('thumbnail_url', models.CharField(blank=True)),
                ('thumbnail_file', models.ImageField(blank=True, help_text='If no thumbnail is provided, one will be generated automatically. You can add a custom one later.', upload_to=video_app.models.video_thumbnail_root)),
                ('category', models.CharField(choices=[('drama', 'Drama'), ('crime', 'Krimi'), ('thriller', 'Thriller'), ('action', 'Action'), ('comedy', 'Komödie'), ('romance', 'Romantik'), ('horror', 'Horror'), ('sci_fi', 'Science-Fiction'), ('fantasy', 'Fantasy'), ('mystery', 'Mystery'), ('adventure', 'Abenteuer'), ('animation', 'Animation'), ('documentary', 'Dokumentarfilm'), ('family', 'Familie'), ('war', 'Krieg'), ('western', 'Western'), ('musical', 'Musical')])),
                ('video_file', models.FileField(help_text='The video file itself cannot be modified after it has been uploaded.', upload_to=video_app.models.video_upload_root)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('ready', 'Ready')], default='pending')),
            ],
        ),
    ]
