# Generated by Django 6.0 on 2026-01-15 06:19

import video_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_app', '0002_video_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='thumbnail_file',
            field=models.ImageField(upload_to=video_app.models.video_thumbnail_root),
        ),
    ]
