# Generated by Django 6.0 on 2026-01-18 07:53

import video_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_app', '0004_alter_video_thumbnail_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='category',
            field=models.CharField(choices=[('drama', 'Drama'), ('crime', 'Krimi'), ('thriller', 'Thriller'), ('action', 'Action'), ('comedy', 'Komödie'), ('romance', 'Romantik'), ('horror', 'Horror'), ('sci_fi', 'Science-Fiction'), ('fantasy', 'Fantasy'), ('mystery', 'Mystery'), ('adventure', 'Abenteuer'), ('animation', 'Animation'), ('documentary', 'Dokumentarfilm'), ('family', 'Familie'), ('war', 'Krieg'), ('western', 'Western'), ('musical', 'Musical')]),
        ),
        migrations.AlterField(
            model_name='video',
            name='video_file',
            field=models.FileField(editable=False, upload_to=video_app.models.video_upload_root),
        ),
    ]
