# Generated by Django 6.0 on 2026-01-18 07:59

import video_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_app', '0005_alter_video_category_alter_video_video_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video_file',
            field=models.FileField(upload_to=video_app.models.video_upload_root),
        ),
    ]
